In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv("Data\\ipl_2025.csv")
# Shape of dataset
print("Shape:", data.shape)
# First 5 rows
print("First 5 rows:\n", data[:5])

Shape: (74, 28)
First 5 rows:
    match_id           date                                          venue  \
0         1  March 22,2025                          Eden Gardens, Kolkata
1         2  March 23,2025  Rajiv Gandhi International Stadium, Hyderabad
2         3  March 23,2025                MA Chidambaram Stadium, Chennai
3         4  March 24,2025       ACA-VDCA Cricket Stadium, Vishakhapatnam
4         5  March 25,2025               Narendra Modi Stadium, Ahmedabad

  team1 team2   stage toss_winner toss_decision  first_ings_score  \
0   KKR   RCB  League         RCB          Bowl             174.0
1   SRH    RR  League          RR          Bowl             286.0
2   CSK    MI  League         CSK          Bowl             155.0
3    DC   LSG  League          DC          Bowl             209.0
4    GT  PBKS  League          GT          Bowl             243.0

   first_ings_wkts  ...       top_scorer  highscore      best_bowling  \
0              8.0  ...      Virat Kohli       59.0     Krunal Pandya
1              6.0  ...     Ishan Kishan      106.0  Tushar Deshpande
2              9.0  ...  Rachin Ravindra       65.0        Noor Ahmad
3              8.0  ...  Nicholas Pooran       75.0    Mitchell Starc
4              5.0  ...     Shreyas Iyer       97.0       Sai Kishore

  best_bowling_figure match_no total_runs_off_bat  total_extras total_wides  \
0               3--29        1              342.0           9.0         5.0
1               3--44        2              497.0          30.0        16.0
2               4--18        3              298.0          15.0         7.0
3               3--42        4              405.0          15.0         8.0
4               3--30        5              449.0          24.0        12.0

  total_noballs  total_wickets
0           0.0           11.0
1           5.0           12.0
2           1.0           15.0
3           1.0           17.0
4           0.0           10.0

[5 rows x 28 columns]

In [2]:
data

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,top_scorer,highscore,best_bowling,best_bowling_figure,match_no,total_runs_off_bat,total_extras,total_wides,total_noballs,total_wickets
0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,8.0,...,Virat Kohli,59.0,Krunal Pandya,3--29,1,342.0,9.0,5.0,0.0,11.0
1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,6.0,...,Ishan Kishan,106.0,Tushar Deshpande,3--44,2,497.0,30.0,16.0,5.0,12.0
2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,9.0,...,Rachin Ravindra,65.0,Noor Ahmad,4--18,3,298.0,15.0,7.0,1.0,15.0
3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,8.0,...,Nicholas Pooran,75.0,Mitchell Starc,3--42,4,405.0,15.0,8.0,1.0,17.0
4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,5.0,...,Shreyas Iyer,97.0,Sai Kishore,3--30,5,449.0,24.0,12.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,70,"May 27,2025","Ekana Cricket Stadium, Lucknow",LSG,RCB,League,RCB,Bowl,227.0,3.0,...,Rishabh Pant,118.0,Will O'Rourke,2--74,70,437.0,20.0,10.0,2.0,7.0
70,71,"May 29,2025","New PCA Cricket Stadium, Mullanpur",PBKS,RCB,Playoffs,RCB,Bowl,101.0,10.0,...,Phil Salt,56.0,Suyash Sharma,3--17,71,192.0,15.0,1.0,1.0,12.0
71,72,"May 30,2025","New PCA Cricket Stadium, Mullanpur",GT,MI,Playoffs,MI,Bat,228.0,5.0,...,Rohit Sharma,81.0,Sai Kishore,2--42,72,419.0,16.0,7.0,0.0,11.0
72,73,"June 1,2025","Narendra Modi Stadium, Ahmedabad",PBKS,MI,Playoffs,PBKS,Bowl,203.0,6.0,...,Shreyas Iyer,87.0,Azmatullah Omarzai,2--43,73,397.0,13.0,7.0,3.0,11.0
73,74,"June 3,2025","Narendra Modi Stadium, Ahmedabad",RCB,PBKS,Final,PBKS,Bowl,190.0,9.0,...,Shashank Singh,61.0,Arshdeep Singh,3--40,74,354.0,20.0,12.0,0.0,16.0

In [3]:
data = data.reset_index()
data["win_by_runs"] = 0

In [4]:
data.head()

,index,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,...,highscore,best_bowling,best_bowling_figure,match_no,total_runs_off_bat,total_extras,total_wides,total_noballs,total_wickets,win_by_runs
0,0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,...,59.0,Krunal Pandya,3--29,1,342.0,9.0,5.0,0.0,11.0,0
1,1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,...,106.0,Tushar Deshpande,3--44,2,497.0,30.0,16.0,5.0,12.0,0
2,2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,...,65.0,Noor Ahmad,4--18,3,298.0,15.0,7.0,1.0,15.0,0
3,3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,...,75.0,Mitchell Starc,3--42,4,405.0,15.0,8.0,1.0,17.0,0
4,4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,...,97.0,Sai Kishore,3--30,5,449.0,24.0,12.0,0.0,10.0,0

In [5]:
data["win_by_runs"] = 0
data["win_by_runs"] = ((data['first_ings_score'] - data['second_ings_score']).clip(lower=0).where((data['match_result'] == "completed"))
)
data

,index,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,...,highscore,best_bowling,best_bowling_figure,match_no,total_runs_off_bat,total_extras,total_wides,total_noballs,total_wickets,win_by_runs
0,0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,...,59.0,Krunal Pandya,3--29,1,342.0,9.0,5.0,0.0,11.0,0.0
1,1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,...,106.0,Tushar Deshpande,3--44,2,497.0,30.0,16.0,5.0,12.0,44.0
2,2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,...,65.0,Noor Ahmad,4--18,3,298.0,15.0,7.0,1.0,15.0,0.0
3,3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,...,75.0,Mitchell Starc,3--42,4,405.0,15.0,8.0,1.0,17.0,0.0
4,4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,...,97.0,Sai Kishore,3--30,5,449.0,24.0,12.0,0.0,10.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,70,"May 27,2025","Ekana Cricket Stadium, Lucknow",LSG,RCB,League,RCB,Bowl,227.0,...,118.0,Will O'Rourke,2--74,70,437.0,20.0,10.0,2.0,7.0,0.0
70,70,71,"May 29,2025","New PCA Cricket Stadium, Mullanpur",PBKS,RCB,Playoffs,RCB,Bowl,101.0,...,56.0,Suyash Sharma,3--17,71,192.0,15.0,1.0,1.0,12.0,0.0
71,71,72,"May 30,2025","New PCA Cricket Stadium, Mullanpur",GT,MI,Playoffs,MI,Bat,228.0,...,81.0,Sai Kishore,2--42,72,419.0,16.0,7.0,0.0,11.0,20.0
72,72,73,"June 1,2025","Narendra Modi Stadium, Ahmedabad",PBKS,MI,Playoffs,PBKS,Bowl,203.0,...,87.0,Azmatullah Omarzai,2--43,73,397.0,13.0,7.0,3.0,11.0,0.0
73,73,74,"June 3,2025","Narendra Modi Stadium, Ahmedabad",RCB,PBKS,Final,PBKS,Bowl,190.0,...,61.0,Arshdeep Singh,3--40,74,354.0,20.0,12.0,0.0,16.0,6.0

In [6]:
data["win_by_wickets"] = (10 - data["second_ings_wkts"].where(data["win_by_runs"] == 0,11))
data

,index,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,...,best_bowling,best_bowling_figure,match_no,total_runs_off_bat,total_extras,total_wides,total_noballs,total_wickets,win_by_runs,win_by_wickets
0,0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,...,Krunal Pandya,3--29,1,342.0,9.0,5.0,0.0,11.0,0.0,7.0
1,1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,...,Tushar Deshpande,3--44,2,497.0,30.0,16.0,5.0,12.0,44.0,-1.0
2,2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,...,Noor Ahmad,4--18,3,298.0,15.0,7.0,1.0,15.0,0.0,4.0
3,3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,...,Mitchell Starc,3--42,4,405.0,15.0,8.0,1.0,17.0,0.0,1.0
4,4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,...,Sai Kishore,3--30,5,449.0,24.0,12.0,0.0,10.0,11.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,70,"May 27,2025","Ekana Cricket Stadium, Lucknow",LSG,RCB,League,RCB,Bowl,227.0,...,Will O'Rourke,2--74,70,437.0,20.0,10.0,2.0,7.0,0.0,6.0
70,70,71,"May 29,2025","New PCA Cricket Stadium, Mullanpur",PBKS,RCB,Playoffs,RCB,Bowl,101.0,...,Suyash Sharma,3--17,71,192.0,15.0,1.0,1.0,12.0,0.0,8.0
71,71,72,"May 30,2025","New PCA Cricket Stadium, Mullanpur",GT,MI,Playoffs,MI,Bat,228.0,...,Sai Kishore,2--42,72,419.0,16.0,7.0,0.0,11.0,20.0,-1.0
72,72,73,"June 1,2025","Narendra Modi Stadium, Ahmedabad",PBKS,MI,Playoffs,PBKS,Bowl,203.0,...,Azmatullah Omarzai,2--43,73,397.0,13.0,7.0,3.0,11.0,0.0,5.0
73,73,74,"June 3,2025","Narendra Modi Stadium, Ahmedabad",RCB,PBKS,Final,PBKS,Bowl,190.0,...,Arshdeep Singh,3--40,74,354.0,20.0,12.0,0.0,16.0,6.0,-1.0

In [7]:
data.shape

(74, 31)

In [8]:
# Assuming win_by_runs is column index 11 and win_by_wickets is index 12 (adjust as per your dataset)
win_by_runs = data['win_by_runs'].astype(float)
win_by_wickets = data['win_by_wickets'].astype(float)

print("Max runs:", np.max(win_by_runs))
print("Min runs:", np.min(win_by_runs))

print("Mean wickets:", np.mean(win_by_wickets))
print("Median wickets:", np.median(win_by_wickets))
print("Std Dev wickets:", np.std(win_by_wickets))

Max runs: 110.0
Min runs: 0.0
Mean wickets: 2.7027027027027026
Median wickets: 0.0
Std Dev wickets: 3.9309229015029366

In [9]:
# Matches where winning team scored more than 50 runs
runs_above_50 = data[win_by_runs > 50]

# Matches decided by wickets (runs = 0)
decided_by_wickets = data[win_by_runs == 0]

In [10]:
# Unique winning teams (assuming column index 10)
winning_teams = data.groupby("match_winner").count()
# First 10 matches won by Mumbai Indians
mi_matches = data[data['match_winner'] =="MI"]

In [11]:
winning_teams.sort_values("match_id",ascending=False)

,index,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,...,best_bowling,best_bowling_figure,match_no,total_runs_off_bat,total_extras,total_wides,total_noballs,total_wickets,win_by_runs,win_by_wickets
match_winner,,,,,,,,,,,,,,,,,,,,,
PBKS,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
RCB,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
GT,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
DC,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
MI,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
SRH,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
LSG,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
KKR,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
CSK,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
RR,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4

In [12]:
# Win margin > 100 runs
margin_gt_100 = np.sum(win_by_runs > 100)

# Margin exactly 0
margin_zero = np.sum(win_by_runs == 0)

In [13]:
margin_gt_100

np.int64(1)

In [14]:
data.to_csv("ipl2025.csv")

In [15]:
data.describe()

,index,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,balls_left,highscore,match_no,total_runs_off_bat,total_extras,total_wides,total_noballs,total_wickets,win_by_runs,win_by_wickets
count,74.000000,74.000000,73.000000,73.000000,72.000000,72.000000,72.000000,71.000000,74.000000,73.000000,73.000000,73.000000,73.000000,73.000000,71.000000,74.000000
mean,36.500000,37.500000,189.753425,6.452055,174.013889,5.513889,10.819444,74.549296,37.500000,345.150685,16.095890,9.013699,0.931507,11.945205,15.535211,2.702703
std,21.505813,21.505813,37.489547,2.108456,38.805217,2.882649,17.674942,20.088226,21.505813,69.194507,6.390454,4.257324,1.158648,3.201087,25.682029,3.957755
min,0.000000,1.000000,95.000000,2.000000,7.000000,0.000000,0.000000,37.000000,1.000000,128.000000,3.000000,1.000000,0.000000,3.000000,0.000000,-1.000000
25%,18.250000,19.250000,166.000000,5.000000,158.000000,3.000000,0.000000,61.000000,19.250000,312.000000,11.000000,6.000000,0.000000,11.000000,0.000000,-1.000000
50%,36.500000,37.500000,196.000000,6.000000,177.000000,5.000000,5.500000,73.000000,37.500000,349.000000,16.000000,9.000000,1.000000,12.000000,0.000000,0.000000
75%,54.750000,55.750000,213.000000,8.000000,201.250000,8.000000,13.500000,88.500000,55.750000,395.000000,21.000000,12.000000,2.000000,14.000000,19.000000,6.750000
max,73.000000,74.000000,286.000000,10.000000,247.000000,10.000000,114.000000,141.000000,74.000000,497.000000,30.000000,23.000000,5.000000,20.000000,110.000000,10.000000